//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BadHabitsStoreEntities : DbContext
    {
        public BadHabitsStoreEntities()
            : base("name=BadHabitsStoreEntities")
        {
        }
        public BadHabitsStoreEntities(string connectionString) : base("name=BadHabitsStoreEntities")
        {
            this.Database.Connection.ConnectionString = connectionString;
        }

        public (bool, string) CanConnect()
        {
            try
            {
                Database.Connection.Open();
                Database.Connection.Close();
            }
            catch (Exception ex)
            {
                return (false, ex.Message);
            }

            return (true, "Connection is OK");
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual DbSet<PurchaseStatusEnum> PurchaseStatusEnums { get; set; }
    }
}
